---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greedylb-scheduler
  namespace: kube-system
  labels:
    app: greedylb-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greedylb-scheduler
  template:
    metadata:
      labels:
        app: greedylb-scheduler
    spec:
      serviceAccountName: custom-scheduler
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
        - name: scheduler
          image: greedylb-scheduler:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SCHEDULER_NAME
              value: "greedylb-scheduler"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
